"""Copy for automatic alerts, SMC/spike scans, and payment failures."""

ALERT_STRINGS = {
    "en": {
        "private_only": "This bot works in a private chat. Open the bot directly and send /start.",
        "set_invalid": "❌ <code>{key}</code> is out of range. Risk is 0.1–5, leverage is 1–100, margin is cross or isolated.",
        "payment_wallet_missing": "⚠️ The payment wallet is not configured. Access was not changed.",
        "payment_expired": "❌ This transfer is outside the 72-hour window and cannot activate access.",
        "payment_wrong_recipient": "❌ This transfer was not sent to the subscription wallet.",
        "payment_wrong_token": "❌ This transfer is not USDT on TRC20.",
        "payment_unconfirmed": "⏳ The transfer is not confirmed yet. Retry /paid in a few minutes.",
        "payment_invalid_amount": "❌ The transfer amount could not be read.",
        "payment_no_invoice": "❌ There is no open invoice. Send /subscribe and pay the exact amount shown there.",
        "payment_save_failed": "⚠️ Payment was not saved. Access was not activated. Retry /paid in a few minutes; the same hash can be used again.",
        "setup_usage": "Usage: <code>/setup BTC</code>",
        "setup_scanning": "🔍 Checking {symbol} for an SMC setup (4h / 1d)...",
        "setup_none": "🤷 No fresh SMC setup for {symbol} on 4h/1d.",
        "spikes_scanning": "🚀 Scanning spikes...",
        "spikes_none": "🤷 No spikes found.",
        "open_chart": "Open chart",
        "request_plan": "Request a plan",
        "retry_setup": "Try again",
        "retry_spikes": "Try again",
        "menu_webapp": "Panel",
        "run_scan": "Scan markets",
        "open_setup": "Open",
        "alert_later": "Later",
        "plan_btc": "BTC plan",
        "open_settings": "Open settings",
        "ready_next": "Deposit saved: <b>{deposit} USDT</b>\nRisk per trade: <b>{risk}%</b>",
        "no_setup_now": "No setup right now.",
        "no_setup_levels": "The levels do not make a plan.",
        "no_setup_data": "There is not enough data for this coin.",
        "no_setup_stale": "The market data is stale.",
        "no_setup_other": "Try another coin.",
        "another_symbol": "Another coin",
        "another_symbol_prompt": "Send a ticker, for example <code>ETH</code>.",
        "size_disclaimer": "The bot calculates the size. You place the order.",
        "tf_1d": "1D trend",
        "tf_4h": "4H trend",
        "tf_struct": "4H structure",
        "tf_regime": "Regime",
        "plan_symbol": "Plan {symbol}",
        "plan_symbol_prompt": "One plan for <b>{symbol}</b>.",
        "listing_na": "n/a",
        "listing_new": (
            "🆕 <b>New MEXC pair: {symbol}</b>\n\n"
            "Coin: <b>{name}</b>\n"
            "CoinGecko rank: #{rank}\n"
            "Market cap: {cap}\n"
            "24h volume: {volume}\n"
            "Risk profile: <b>{risk}</b>\n\n"
            "⚠️ New listings often move sharply. Do not enter without a plan and a stop."
        ),
        "listing_news": (
            "📰 <b>MEXC listing news</b>\n\n"
            "<b>{title}</b>\n"
            "Tickers: <b>{symbols}</b>\n"
            "Published: {published}\n\n"
            "Coin: <b>{name}</b>\n"
            "CoinGecko rank: #{rank}\n"
            "Market cap: {cap}\n"
            "24h volume: {volume}\n"
            "Risk profile: <b>{risk}</b>\n\n"
            "Link: {url}"
        ),
        "coin_missing": "❌ {coin} was not found on MEXC.",
        "command_error": "❌ Error: {error}",
        "analysis_running": "🤖 Deep analysis of {symbol} (15m→1w)...",
        "alert_signal": "SIGNAL",
        "alert_price_now": "Price now",
        "alert_regime": "Regime",
        "alert_trend": "1D trend",
        "alert_confidence": "Confidence",
        "alert_entry": "Entry",
        "alert_stop": "Stop",
        "alert_from_entry": "from entry",
        "alert_deposit": "Deposit",
        "alert_position": "Position size",
        "alert_margin": "Margin required",
        "alert_risk": "Stop risk",
        "alert_contracts": "MEXC contracts",
        "alert_lev_capped": "Leverage was reduced to the MEXC maximum for this market.",
        "alert_min_contract": "The minimum MEXC contract is too large for this risk. Do not open the trade.",
        "alert_reference": "Sized on a 1 000 USDT example. Set your deposit with /start for a personal amount.",
        "alert_more": "Details:",
        "spike_title": "SPIKE",
        "spike_long": "🟢 LONG (pump)",
        "spike_short": "🔴 SHORT (dump)",
        "spike_direction": "Direction",
        "spike_quality": "Quality",
        "spike_timeframe": "Timeframe",
        "spike_price_before": "Price before",
        "spike_price_now": "Price now",
        "spike_change": "Price change",
        "spike_volume": "Candle volume vs average",
        "spike_coin": "Coin",
        "spike_risk": "Risk profile",
        "spike_type": "Coin type",
        "spike_why": "Why this matters",
        "spike_risks": "Risks",
        "smc_title": "SMC SETUP",
        "smc_direction": "Direction",
        "smc_pattern": "Pattern",
        "smc_analysis": "Context",
        "smc_regime": "Regime",
        "smc_phase": "Phase",
        "smc_setup_type": "Setup type",
        "smc_risks": "Risk factors",
        "smc_no_risk": "No extra risk flags",
        "smc_entry": "Entry",
        "smc_stop": "Stop",
        "smc_tp": "Take profit",
        "analysis_title": "MULTI-TIMEFRAME ANALYSIS",
        "analysis_macro": "Macro trend (1W)",
        "analysis_active": "Active trend (1D)",
        "analysis_setup": "Setup (4H)",
        "analysis_confirm": "Confirmation (1H)",
        "analysis_trigger": "Trigger (15m)",
        "analysis_confidence": "MTF confidence",
        "analysis_clean": "Timeframes are aligned",
        "analysis_zones": "Nearby zones (1h)",
        "analysis_no_fvg": "No nearby imbalance.",
        "analysis_liquidity": "Liquidity (15m)",
        "analysis_opinion": "Read",
        "analysis_high": "Trends agree. Trade only in the macro direction from a nearby zone, with a stop.",
        "analysis_mid": "Timeframes are mostly aligned. If you trade, use a smaller risk.",
        "analysis_low": "The picture is mixed. Counter-trend bounces and weak structure are present.",
        "analysis_none": "Timeframes conflict. Standing aside is the cleaner choice until structure is clear.",
        "bias_bull": "Bullish",
        "bias_bear": "Bearish",
        "liq_buy": "Buy-side stops",
        "liq_sell": "Sell-side stops",
        "term_bullish": "Bullish",
        "term_bearish": "Bearish",
        "term_neutral": "Neutral",
        "term_bullish_continuation": "Bullish continuation",
        "term_bearish_continuation": "Bearish continuation",
        "term_bullish_reversal": "Bullish reversal",
        "term_bearish_reversal": "Bearish reversal",
        "term_counter_trend_bounce": "Counter-trend bounce",
        "term_no_trade": "No trade",
        "term_strong": "Strong",
        "term_moderate": "Moderate",
        "term_weak": "Weak",
        "term_conflicting": "Conflicting",
        "term_aligned": "Aligned",
        "term_pending": "Pending",
        "term_noisy": "Noisy",
        "term_countertrend_to_macro": "Trade is against the macro trend",
        "term_countertrend_context": "Local price action does not support the setup",
        "term_neutral or mixed macro context": "Higher timeframes are mixed",
        "term_setup conflicts with active bias": "Setup conflicts with the daily trend",
        "term_weak_confirmation": "Weak confirmation",
        "term_noisy structure": "Noisy local structure",
        "term_choppy range environment": "Choppy range",
    },
    "ru": {
        "private_only": "Бот работает только в личном чате. Открой диалог с ботом и отправь /start.",
        "set_invalid": "❌ <code>{key}</code> вне диапазона. Риск 0.1–5, плечо 1–100, маржа cross или isolated.",
        "payment_wallet_missing": "⚠️ Кошелёк для оплаты не настроен. Доступ не изменён.",
        "payment_expired": "❌ Перевод старше 72 часов и не может включить доступ.",
        "payment_wrong_recipient": "❌ Перевод отправлен не на кошелёк подписки.",
        "payment_wrong_token": "❌ Это не USDT в сети TRC20.",
        "payment_unconfirmed": "⏳ Перевод ещё не подтверждён. Повтори /paid через несколько минут.",
        "payment_invalid_amount": "❌ Не удалось прочитать сумму перевода.",
        "payment_no_invoice": "❌ Нет открытого счёта. Отправь /subscribe и оплати точную сумму оттуда.",
        "payment_save_failed": "⚠️ Оплата не сохранилась. Доступ не включён. Повтори /paid через несколько минут — тот же хеш можно отправить снова.",
        "setup_usage": "Использование: <code>/setup BTC</code>",
        "setup_scanning": "🔍 Проверяю SMC-сетап {symbol} (4h / 1d)...",
        "setup_none": "🤷 Нет свежего SMC-сетапа по {symbol} на 4h/1d.",
        "spikes_scanning": "🚀 Сканирую всплески...",
        "spikes_none": "🤷 Аномалий не найдено.",
        "open_chart": "Открыть график",
        "request_plan": "Запросить план",
        "retry_setup": "Повторить",
        "retry_spikes": "Повторить",
        "menu_webapp": "Панель",
        "run_scan": "Сканировать",
        "open_setup": "Открыть",
        "alert_later": "Позже",
        "plan_btc": "План по BTC",
        "open_settings": "Открыть настройки",
        "ready_next": "Депозит сохранён: <b>{deposit} USDT</b>\nРиск на сделку: <b>{risk}%</b>",
        "no_setup_now": "Сетапа сейчас нет.",
        "no_setup_levels": "Уровни не складываются в план.",
        "no_setup_data": "По этой монете недостаточно данных.",
        "no_setup_stale": "Данные рынка устарели.",
        "no_setup_other": "Попробуй другую монету.",
        "another_symbol": "Другая монета",
        "another_symbol_prompt": "Напиши тикер, например <code>ETH</code>.",
        "size_disclaimer": "Бот считает размер. Ордер ставишь ты.",
        "tf_1d": "Тренд 1Д",
        "tf_4h": "Тренд 4Ч",
        "tf_struct": "Структура 4Ч",
        "tf_regime": "Режим",
        "plan_symbol": "План {symbol}",
        "plan_symbol_prompt": "Один план по <b>{symbol}</b>.",
        "listing_na": "н/д",
        "listing_new": (
            "🆕 <b>Новая пара на MEXC: {symbol}</b>\n\n"
            "Монета: <b>{name}</b>\n"
            "Рейтинг CoinGecko: #{rank}\n"
            "Market Cap: {cap}\n"
            "24h Volume: {volume}\n"
            "Риск-профиль: <b>{risk}</b>\n\n"
            "⚠️ Новые листинги часто двигаются резко. Не входи без плана и стопа."
        ),
        "listing_news": (
            "📰 <b>Новость MEXC по листингу</b>\n\n"
            "<b>{title}</b>\n"
            "Тикеры: <b>{symbols}</b>\n"
            "Опубликовано: {published}\n\n"
            "Монета: <b>{name}</b>\n"
            "Рейтинг CoinGecko: #{rank}\n"
            "Market Cap: {cap}\n"
            "24h Volume: {volume}\n"
            "Риск-профиль: <b>{risk}</b>\n\n"
            "Ссылка: {url}"
        ),
        "coin_missing": "❌ {coin} не найдена на MEXC.",
        "command_error": "❌ Ошибка: {error}",
        "analysis_running": "🤖 Глубокий анализ {symbol} (15m→1w)...",
        "alert_signal": "СИГНАЛ",
        "alert_price_now": "Цена сейчас",
        "alert_regime": "Режим",
        "alert_trend": "Тренд 1D",
        "alert_confidence": "Уверенность",
        "alert_entry": "Вход",
        "alert_stop": "Стоп",
        "alert_from_entry": "от входа",
        "alert_deposit": "Депозит",
        "alert_position": "Объём позиции",
        "alert_margin": "Нужно маржи",
        "alert_risk": "Риск по стопу",
        "alert_contracts": "Контрактов MEXC",
        "alert_lev_capped": "Плечо снижено до максимума MEXC для этой монеты.",
        "alert_min_contract": "Минимальный контракт MEXC слишком велик для этого риска. Сделку открывать не нужно.",
        "alert_reference": "Расчёт на примере 1 000 USDT. Укажи свой депозит через /start.",
        "alert_more": "Подробнее:",
        "spike_title": "СПАЙК",
        "spike_long": "🟢 LONG (памп)",
        "spike_short": "🔴 SHORT (дамп)",
        "spike_direction": "Направление",
        "spike_quality": "Качество",
        "spike_timeframe": "Таймфрейм",
        "spike_price_before": "Цена до",
        "spike_price_now": "Цена сейчас",
        "spike_change": "Изменение цены",
        "spike_volume": "Объём свечи к среднему",
        "spike_coin": "Монета",
        "spike_risk": "Риск-профиль",
        "spike_type": "Тип монеты",
        "spike_why": "Почему это важно",
        "spike_risks": "Риски",
        "smc_title": "SMC СЕТАП",
        "smc_direction": "Направление",
        "smc_pattern": "Паттерн",
        "smc_analysis": "Контекст",
        "smc_regime": "Режим",
        "smc_phase": "Фаза",
        "smc_setup_type": "Тип сетапа",
        "smc_risks": "Факторы риска",
        "smc_no_risk": "Дополнительных флагов риска нет",
        "smc_entry": "Вход",
        "smc_stop": "Стоп",
        "smc_tp": "Тейк-профит",
        "analysis_title": "АНАЛИЗ ПО ТАЙМФРЕЙМАМ",
        "analysis_macro": "Макро-тренд (1W)",
        "analysis_active": "Активный тренд (1D)",
        "analysis_setup": "Сетап (4H)",
        "analysis_confirm": "Подтверждение (1H)",
        "analysis_trigger": "Триггер (15m)",
        "analysis_confidence": "Уверенность MTF",
        "analysis_clean": "Таймфреймы согласованы",
        "analysis_zones": "Ближайшие зоны (1h)",
        "analysis_no_fvg": "Явного имбаланса рядом нет.",
        "analysis_liquidity": "Ликвидность (15m)",
        "analysis_opinion": "Вывод",
        "analysis_high": "Тренды совпадают. Торговать имеет смысл только по макро-направлению от ближайшей зоны и со стопом.",
        "analysis_mid": "Таймфреймы в основном совпадают. Если входить, риск лучше снизить.",
        "analysis_low": "Картина смешанная: есть контртрендовые отскоки или слабая структура.",
        "analysis_none": "Таймфреймы конфликтуют. До ясной структуры разумнее остаться вне рынка.",
        "bias_bull": "Бычий",
        "bias_bear": "Медвежий",
        "liq_buy": "Buy-side стопы",
        "liq_sell": "Sell-side стопы",
        "term_bullish": "Бычий",
        "term_bearish": "Медвежий",
        "term_neutral": "Нейтральный",
        "term_bullish_continuation": "Продолжение роста",
        "term_bearish_continuation": "Продолжение падения",
        "term_bullish_reversal": "Бычий разворот",
        "term_bearish_reversal": "Медвежий разворот",
        "term_counter_trend_bounce": "Контртрендовый отскок",
        "term_no_trade": "Вне рынка",
        "term_strong": "Сильное",
        "term_moderate": "Умеренное",
        "term_weak": "Слабое",
        "term_conflicting": "Противоречивое",
        "term_aligned": "Сформирован",
        "term_pending": "Формируется",
        "term_noisy": "Шум",
        "term_countertrend_to_macro": "Сделка против макро-тренда",
        "term_countertrend_context": "Локальное движение не поддерживает сетап",
        "term_neutral or mixed macro context": "Старшие таймфреймы смешанные",
        "term_setup conflicts with active bias": "Сетап против дневного тренда",
        "term_weak_confirmation": "Слабое подтверждение",
        "term_noisy structure": "Шумная структура",
        "term_choppy range environment": "Узкий диапазон",
    },
    "de": {
        "private_only": "Dieser Bot funktioniert nur im privaten Chat. Öffne den Bot direkt und sende /start.",
        "set_invalid": "❌ <code>{key}</code> ist außerhalb des Bereichs. Risiko 0,1–5, Hebel 1–100, Margin cross oder isolated.",
        "payment_wallet_missing": "⚠️ Die Zahlungs-Wallet ist nicht konfiguriert. Der Zugang wurde nicht geändert.",
        "payment_expired": "❌ Diese Überweisung liegt außerhalb von 72 Stunden und aktiviert keinen Zugang.",
        "payment_wrong_recipient": "❌ Diese Überweisung ging nicht an die Abo-Wallet.",
        "payment_wrong_token": "❌ Das ist kein USDT im TRC20-Netz.",
        "payment_unconfirmed": "⏳ Die Überweisung ist noch nicht bestätigt. Versuche /paid in ein paar Minuten erneut.",
        "payment_invalid_amount": "❌ Der Betrag konnte nicht gelesen werden.",
        "payment_no_invoice": "❌ Es gibt keine offene Rechnung. Sende /subscribe und zahle den exakten Betrag.",
        "payment_save_failed": "⚠️ Die Zahlung wurde nicht gespeichert. Der Zugang ist nicht aktiv. Versuche /paid erneut; derselbe Hash bleibt gültig.",
        "setup_usage": "Verwendung: <code>/setup BTC</code>",
        "setup_scanning": "🔍 Prüfe {symbol} auf ein SMC-Setup (4h / 1d)...",
        "setup_none": "🤷 Kein frisches SMC-Setup für {symbol} auf 4h/1d.",
        "spikes_scanning": "🚀 Suche Spikes...",
        "spikes_none": "🤷 Keine Spikes gefunden.",
        "open_chart": "Chart öffnen",
        "request_plan": "Plan anfordern",
        "retry_setup": "Erneut versuchen",
        "retry_spikes": "Erneut versuchen",
        "menu_webapp": "Panel",
        "run_scan": "Märkte scannen",
        "open_setup": "Öffnen",
        "alert_later": "Später",
        "plan_btc": "Plan für BTC",
        "open_settings": "Einstellungen öffnen",
        "ready_next": "Kapital gespeichert: <b>{deposit} USDT</b>\nRisiko pro Trade: <b>{risk}%</b>",
        "no_setup_now": "Gerade kein Setup.",
        "no_setup_levels": "Die Levels ergeben keinen Plan.",
        "no_setup_data": "Für diese Coin fehlen Daten.",
        "no_setup_stale": "Die Marktdaten sind veraltet.",
        "no_setup_other": "Versuch eine andere Coin.",
        "another_symbol": "Andere Coin",
        "another_symbol_prompt": "Schick ein Kürzel, zum Beispiel <code>ETH</code>.",
        "size_disclaimer": "Der Bot berechnet die Größe. Die Order setzt du.",
        "tf_1d": "Trend 1D",
        "tf_4h": "Trend 4H",
        "tf_struct": "Struktur 4H",
        "tf_regime": "Regime",
        "plan_symbol": "Plan {symbol}",
        "plan_symbol_prompt": "Ein Plan für <b>{symbol}</b>.",
        "listing_na": "k. A.",
        "listing_new": (
            "🆕 <b>Neues MEXC-Paar: {symbol}</b>\n\n"
            "Coin: <b>{name}</b>\n"
            "CoinGecko-Rang: #{rank}\n"
            "Marktkapitalisierung: {cap}\n"
            "24h-Volumen: {volume}\n"
            "Risikoprofil: <b>{risk}</b>\n\n"
            "⚠️ Neue Listings bewegen sich oft stark. Nicht ohne Plan und Stop einsteigen."
        ),
        "listing_news": (
            "📰 <b>MEXC-Listing-News</b>\n\n"
            "<b>{title}</b>\n"
            "Ticker: <b>{symbols}</b>\n"
            "Veröffentlicht: {published}\n\n"
            "Coin: <b>{name}</b>\n"
            "CoinGecko-Rang: #{rank}\n"
            "Marktkapitalisierung: {cap}\n"
            "24h-Volumen: {volume}\n"
            "Risikoprofil: <b>{risk}</b>\n\n"
            "Link: {url}"
        ),
        "coin_missing": "❌ {coin} wurde auf MEXC nicht gefunden.",
        "command_error": "❌ Fehler: {error}",
        "analysis_running": "🤖 Tiefenanalyse von {symbol} (15m→1w)...",
        "alert_signal": "SIGNAL",
        "alert_price_now": "Preis jetzt",
        "alert_regime": "Regime",
        "alert_trend": "1D-Trend",
        "alert_confidence": "Konfidenz",
        "alert_entry": "Einstieg",
        "alert_stop": "Stop",
        "alert_from_entry": "vom Einstieg",
        "alert_deposit": "Kapital",
        "alert_position": "Positionsgröße",
        "alert_margin": "Benötigte Margin",
        "alert_risk": "Stop-Risiko",
        "alert_contracts": "MEXC-Kontrakte",
        "alert_lev_capped": "Der Hebel wurde auf das MEXC-Maximum für diesen Markt gesenkt.",
        "alert_min_contract": "Der minimale MEXC-Kontrakt ist für dieses Risiko zu groß. Trade nicht eröffnen.",
        "alert_reference": "Beispielrechnung mit 1 000 USDT. Lege dein Kapital mit /start fest.",
        "alert_more": "Details:",
        "spike_title": "SPIKE",
        "spike_long": "🟢 LONG (Pump)",
        "spike_short": "🔴 SHORT (Dump)",
        "spike_direction": "Richtung",
        "spike_quality": "Qualität",
        "spike_timeframe": "Zeitrahmen",
        "spike_price_before": "Preis davor",
        "spike_price_now": "Preis jetzt",
        "spike_change": "Preisänderung",
        "spike_volume": "Kerzvolumen gegen Durchschnitt",
        "spike_coin": "Coin",
        "spike_risk": "Risikoprofil",
        "spike_type": "Coin-Typ",
        "spike_why": "Warum das zählt",
        "spike_risks": "Risiken",
        "smc_title": "SMC-SETUP",
        "smc_direction": "Richtung",
        "smc_pattern": "Muster",
        "smc_analysis": "Kontext",
        "smc_regime": "Regime",
        "smc_phase": "Phase",
        "smc_setup_type": "Setup-Typ",
        "smc_risks": "Risikofaktoren",
        "smc_no_risk": "Keine zusätzlichen Risikofaktoren",
        "smc_entry": "Einstieg",
        "smc_stop": "Stop",
        "smc_tp": "Take-Profit",
        "analysis_title": "MULTI-TIMEFRAME-ANALYSE",
        "analysis_macro": "Makrotrend (1W)",
        "analysis_active": "Aktiver Trend (1D)",
        "analysis_setup": "Setup (4H)",
        "analysis_confirm": "Bestätigung (1H)",
        "analysis_trigger": "Trigger (15m)",
        "analysis_confidence": "MTF-Konfidenz",
        "analysis_clean": "Zeitrahmen sind synchron",
        "analysis_zones": "Nahe Zonen (1h)",
        "analysis_no_fvg": "Kein nahes Ungleichgewicht.",
        "analysis_liquidity": "Liquidität (15m)",
        "analysis_opinion": "Einschätzung",
        "analysis_high": "Die Trends stimmen überein. Nur in Makro-Richtung von einer nahen Zone und mit Stop handeln.",
        "analysis_mid": "Die Zeitrahmen stimmen weitgehend überein. Wenn du handelst, nimm weniger Risiko.",
        "analysis_low": "Das Bild ist gemischt. Gegentrend-Bewegungen oder schwache Struktur sind sichtbar.",
        "analysis_none": "Die Zeitrahmen widersprechen sich. Abwarten ist die sauberere Wahl.",
        "bias_bull": "Bullisch",
        "bias_bear": "Bärisch",
        "liq_buy": "Buy-Side-Stops",
        "liq_sell": "Sell-Side-Stops",
    },
    "fr": {
        "private_only": "Ce bot fonctionne dans un chat privé. Ouvre le bot directement et envoie /start.",
        "set_invalid": "❌ <code>{key}</code> est hors limites. Risque 0,1–5, levier 1–100, marge cross ou isolated.",
        "payment_wallet_missing": "⚠️ Le portefeuille de paiement n'est pas configuré. L'accès n'a pas changé.",
        "payment_expired": "❌ Ce transfert est hors de la fenêtre de 72 heures et ne peut pas activer l'accès.",
        "payment_wrong_recipient": "❌ Ce transfert n'a pas été envoyé au portefeuille d'abonnement.",
        "payment_wrong_token": "❌ Ce n'est pas de l'USDT sur TRC20.",
        "payment_unconfirmed": "⏳ Le transfert n'est pas encore confirmé. Réessaie /paid dans quelques minutes.",
        "payment_invalid_amount": "❌ Le montant du transfert n'a pas pu être lu.",
        "payment_no_invoice": "❌ Aucune facture ouverte. Envoie /subscribe et paie le montant exact.",
        "payment_save_failed": "⚠️ Le paiement n'a pas été enregistré. L'accès n'est pas actif. Réessaie /paid ; le même hash reste utilisable.",
        "setup_usage": "Utilisation : <code>/setup BTC</code>",
        "setup_scanning": "🔍 Analyse SMC de {symbol} (4h / 1d)...",
        "setup_none": "🤷 Pas de setup SMC récent pour {symbol} en 4h/1d.",
        "spikes_scanning": "🚀 Recherche de spikes...",
        "spikes_none": "🤷 Aucun spike trouvé.",
        "open_chart": "Ouvrir le graphique",
        "request_plan": "Demander un plan",
        "retry_setup": "Réessayer",
        "retry_spikes": "Réessayer",
        "menu_webapp": "Panneau",
        "run_scan": "Scanner les marchés",
        "open_setup": "Ouvrir",
        "alert_later": "Plus tard",
        "plan_btc": "Plan BTC",
        "open_settings": "Ouvrir les réglages",
        "ready_next": "Dépôt enregistré : <b>{deposit} USDT</b>\nRisque par trade : <b>{risk} %</b>",
        "no_setup_now": "Pas de setup pour le moment.",
        "no_setup_levels": "Les niveaux ne forment pas un plan.",
        "no_setup_data": "Il n'y a pas assez de données pour cette pièce.",
        "no_setup_stale": "Les données de marché sont périmées.",
        "no_setup_other": "Essaie une autre pièce.",
        "another_symbol": "Autre pièce",
        "another_symbol_prompt": "Envoie un ticker, par exemple <code>ETH</code>.",
        "size_disclaimer": "Le bot calcule la taille. Tu passes l'ordre.",
        "tf_1d": "Tendance 1J",
        "tf_4h": "Tendance 4H",
        "tf_struct": "Structure 4H",
        "tf_regime": "Régime",
        "plan_symbol": "Plan {symbol}",
        "plan_symbol_prompt": "Un plan pour <b>{symbol}</b>.",
        "listing_na": "n/d",
        "listing_new": (
            "🆕 <b>Nouvelle paire MEXC : {symbol}</b>\n\n"
            "Monnaie : <b>{name}</b>\n"
            "Rang CoinGecko : #{rank}\n"
            "Capitalisation : {cap}\n"
            "Volume 24h : {volume}\n"
            "Profil de risque : <b>{risk}</b>\n\n"
            "⚠️ Les nouveaux listings bougent souvent fort. N'entre pas sans plan ni stop."
        ),
        "listing_news": (
            "📰 <b>Actualité de listing MEXC</b>\n\n"
            "<b>{title}</b>\n"
            "Tickers : <b>{symbols}</b>\n"
            "Publié : {published}\n\n"
            "Monnaie : <b>{name}</b>\n"
            "Rang CoinGecko : #{rank}\n"
            "Capitalisation : {cap}\n"
            "Volume 24h : {volume}\n"
            "Profil de risque : <b>{risk}</b>\n\n"
            "Lien : {url}"
        ),
        "coin_missing": "❌ {coin} est introuvable sur MEXC.",
        "command_error": "❌ Erreur : {error}",
        "analysis_running": "🤖 Analyse approfondie de {symbol} (15m→1w)...",
        "alert_signal": "SIGNAL",
        "alert_price_now": "Prix actuel",
        "alert_regime": "Régime",
        "alert_trend": "Tendance 1D",
        "alert_confidence": "Confiance",
        "alert_entry": "Entrée",
        "alert_stop": "Stop",
        "alert_from_entry": "depuis l'entrée",
        "alert_deposit": "Dépôt",
        "alert_position": "Taille de position",
        "alert_margin": "Marge requise",
        "alert_risk": "Risque au stop",
        "alert_contracts": "Contrats MEXC",
        "alert_lev_capped": "Le levier a été réduit au maximum MEXC de ce marché.",
        "alert_min_contract": "Le contrat minimum MEXC est trop grand pour ce risque. N'ouvre pas le trade.",
        "alert_reference": "Exemple calculé sur 1 000 USDT. Indique ton dépôt avec /start.",
        "alert_more": "Détails :",
        "spike_title": "SPIKE",
        "spike_long": "🟢 LONG (pump)",
        "spike_short": "🔴 SHORT (dump)",
        "spike_direction": "Direction",
        "spike_quality": "Qualité",
        "spike_timeframe": "Unité de temps",
        "spike_price_before": "Prix avant",
        "spike_price_now": "Prix actuel",
        "spike_change": "Variation",
        "spike_volume": "Volume de bougie vs moyenne",
        "spike_coin": "Jeton",
        "spike_risk": "Profil de risque",
        "spike_type": "Type de jeton",
        "spike_why": "Pourquoi c'est important",
        "spike_risks": "Risques",
        "smc_title": "SETUP SMC",
        "smc_direction": "Direction",
        "smc_pattern": "Figure",
        "smc_analysis": "Contexte",
        "smc_regime": "Régime",
        "smc_phase": "Phase",
        "smc_setup_type": "Type de setup",
        "smc_risks": "Facteurs de risque",
        "smc_no_risk": "Pas de facteur de risque supplémentaire",
        "smc_entry": "Entrée",
        "smc_stop": "Stop",
        "smc_tp": "Take-profit",
        "analysis_title": "ANALYSE MULTI-UNITÉS",
        "analysis_macro": "Tendance macro (1W)",
        "analysis_active": "Tendance active (1D)",
        "analysis_setup": "Setup (4H)",
        "analysis_confirm": "Confirmation (1H)",
        "analysis_trigger": "Déclencheur (15m)",
        "analysis_confidence": "Confiance MTF",
        "analysis_clean": "Les unités de temps sont alignées",
        "analysis_zones": "Zones proches (1h)",
        "analysis_no_fvg": "Pas de déséquilibre proche.",
        "analysis_liquidity": "Liquidité (15m)",
        "analysis_opinion": "Lecture",
        "analysis_high": "Les tendances concordent. Trader seulement dans le sens macro, depuis une zone proche, avec un stop.",
        "analysis_mid": "Les unités de temps sont globalement alignées. Si tu trades, réduis le risque.",
        "analysis_low": "L'image est mixte. Il y a des rebonds contre-tendance ou une structure faible.",
        "analysis_none": "Les unités de temps se contredisent. Rester à l'écart est le choix le plus propre.",
        "bias_bull": "Haussier",
        "bias_bear": "Baissier",
        "liq_buy": "Stops buy-side",
        "liq_sell": "Stops sell-side",
    },
    "es": {
        "private_only": "Este bot funciona en un chat privado. Abre el bot directamente y envía /start.",
        "set_invalid": "❌ <code>{key}</code> está fuera de rango. Riesgo 0.1–5, apalancamiento 1–100, margen cross o isolated.",
        "payment_wallet_missing": "⚠️ La billetera de pago no está configurada. El acceso no cambió.",
        "payment_expired": "❌ Esta transferencia está fuera de la ventana de 72 horas y no activa el acceso.",
        "payment_wrong_recipient": "❌ Esta transferencia no se envió a la billetera de la suscripción.",
        "payment_wrong_token": "❌ No es USDT en la red TRC20.",
        "payment_unconfirmed": "⏳ La transferencia aún no está confirmada. Repite /paid en unos minutos.",
        "payment_invalid_amount": "❌ No se pudo leer el importe de la transferencia.",
        "payment_no_invoice": "❌ No hay una factura abierta. Envía /subscribe y paga el importe exacto.",
        "payment_save_failed": "⚠️ El pago no se guardó. El acceso no se activó. Repite /paid; el mismo hash sigue siendo válido.",
        "setup_usage": "Uso: <code>/setup BTC</code>",
        "setup_scanning": "🔍 Revisando setup SMC de {symbol} (4h / 1d)...",
        "setup_none": "🤷 No hay un setup SMC reciente para {symbol} en 4h/1d.",
        "spikes_scanning": "🚀 Buscando spikes...",
        "spikes_none": "🤷 No se encontraron spikes.",
        "open_chart": "Abrir gráfico",
        "request_plan": "Pedir un plan",
        "retry_setup": "Reintentar",
        "retry_spikes": "Reintentar",
        "menu_webapp": "Panel",
        "run_scan": "Escanear mercados",
        "open_setup": "Abrir",
        "alert_later": "Después",
        "plan_btc": "Plan de BTC",
        "open_settings": "Abrir ajustes",
        "ready_next": "Depósito guardado: <b>{deposit} USDT</b>\nRiesgo por operación: <b>{risk}%</b>",
        "no_setup_now": "Ahora no hay setup.",
        "no_setup_levels": "Los niveles no forman un plan.",
        "no_setup_data": "No hay datos suficientes para esta moneda.",
        "no_setup_stale": "Los datos de mercado están desactualizados.",
        "no_setup_other": "Prueba otra moneda.",
        "another_symbol": "Otra moneda",
        "another_symbol_prompt": "Envía un ticker, por ejemplo <code>ETH</code>.",
        "size_disclaimer": "El bot calcula el tamaño. La orden la pones tú.",
        "tf_1d": "Tendencia 1D",
        "tf_4h": "Tendencia 4H",
        "tf_struct": "Estructura 4H",
        "tf_regime": "Régimen",
        "plan_symbol": "Plan {symbol}",
        "plan_symbol_prompt": "Un plan para <b>{symbol}</b>.",
        "listing_na": "n/d",
        "listing_new": (
            "🆕 <b>Nuevo par en MEXC: {symbol}</b>\n\n"
            "Moneda: <b>{name}</b>\n"
            "Ranking CoinGecko: #{rank}\n"
            "Capitalización: {cap}\n"
            "Volumen 24h: {volume}\n"
            "Perfil de riesgo: <b>{risk}</b>\n\n"
            "⚠️ Los listados nuevos se mueven con fuerza. No entres sin un plan y un stop."
        ),
        "listing_news": (
            "📰 <b>Noticia de listado en MEXC</b>\n\n"
            "<b>{title}</b>\n"
            "Tickers: <b>{symbols}</b>\n"
            "Publicado: {published}\n\n"
            "Moneda: <b>{name}</b>\n"
            "Ranking CoinGecko: #{rank}\n"
            "Capitalización: {cap}\n"
            "Volumen 24h: {volume}\n"
            "Perfil de riesgo: <b>{risk}</b>\n\n"
            "Enlace: {url}"
        ),
        "coin_missing": "❌ {coin} no se encontró en MEXC.",
        "command_error": "❌ Error: {error}",
        "analysis_running": "🤖 Análisis profundo de {symbol} (15m→1w)...",
        "alert_signal": "SEÑAL",
        "alert_price_now": "Precio actual",
        "alert_regime": "Régimen",
        "alert_trend": "Tendencia 1D",
        "alert_confidence": "Confianza",
        "alert_entry": "Entrada",
        "alert_stop": "Stop",
        "alert_from_entry": "desde la entrada",
        "alert_deposit": "Depósito",
        "alert_position": "Tamaño de posición",
        "alert_margin": "Margen necesario",
        "alert_risk": "Riesgo al stop",
        "alert_contracts": "Contratos MEXC",
        "alert_lev_capped": "El apalancamiento se redujo al máximo de MEXC para este mercado.",
        "alert_min_contract": "El contrato mínimo de MEXC es demasiado grande para este riesgo. No abras la operación.",
        "alert_reference": "Cálculo de ejemplo con 1 000 USDT. Indica tu depósito con /start.",
        "alert_more": "Detalle:",
        "spike_title": "SPIKE",
        "spike_long": "🟢 LONG (pump)",
        "spike_short": "🔴 SHORT (dump)",
        "spike_direction": "Dirección",
        "spike_quality": "Calidad",
        "spike_timeframe": "Temporalidad",
        "spike_price_before": "Precio antes",
        "spike_price_now": "Precio actual",
        "spike_change": "Cambio de precio",
        "spike_volume": "Volumen de vela frente a la media",
        "spike_coin": "Moneda",
        "spike_risk": "Perfil de riesgo",
        "spike_type": "Tipo de moneda",
        "spike_why": "Por qué importa",
        "spike_risks": "Riesgos",
        "smc_title": "SETUP SMC",
        "smc_direction": "Dirección",
        "smc_pattern": "Patrón",
        "smc_analysis": "Contexto",
        "smc_regime": "Régimen",
        "smc_phase": "Fase",
        "smc_setup_type": "Tipo de setup",
        "smc_risks": "Factores de riesgo",
        "smc_no_risk": "Sin factores de riesgo extra",
        "smc_entry": "Entrada",
        "smc_stop": "Stop",
        "smc_tp": "Take profit",
        "analysis_title": "ANÁLISIS MULTITEMPORAL",
        "analysis_macro": "Tendencia macro (1W)",
        "analysis_active": "Tendencia activa (1D)",
        "analysis_setup": "Setup (4H)",
        "analysis_confirm": "Confirmación (1H)",
        "analysis_trigger": "Disparo (15m)",
        "analysis_confidence": "Confianza MTF",
        "analysis_clean": "Las temporalidades están alineadas",
        "analysis_zones": "Zonas cercanas (1h)",
        "analysis_no_fvg": "No hay un desequilibrio cercano.",
        "analysis_liquidity": "Liquidez (15m)",
        "analysis_opinion": "Lectura",
        "analysis_high": "Las tendencias coinciden. Opera solo a favor del macro, desde una zona cercana y con stop.",
        "analysis_mid": "Las temporalidades coinciden en general. Si operas, usa menos riesgo.",
        "analysis_low": "La imagen es mixta. Hay rebotes contra tendencia o estructura débil.",
        "analysis_none": "Las temporalidades se contradicen. Quedarse fuera es la opción más limpia.",
        "bias_bull": "Alcista",
        "bias_bear": "Bajista",
        "liq_buy": "Stops buy-side",
        "liq_sell": "Stops sell-side",
    },
}
